### ISSUE TITLE
GNU Octave compatibility

### ISSUE THREAD

**Issue by KaeroDot** [witkovsky/OEFPIL-MATLAB#2]
By a first check, scripts seems to be compatible to GNU Octave (super!) but one thing:
After the calculations a table is being made (in OEFPIL.m line 580) `TABLE_beta = table;`. The `table` function is not yet implemented in GNU Octave yet.
Because this part only formats results and is not necessary for calculation, it could be fully enclosed by `options.verbose`, thus achieving compatibility. The more complex variant would be to not use `table` function at all.

Compatibility with GNU Octave is important not only because of free, open-source code, but also because of code portability. Matlab is not available on all platforms.

**Comment by witkovsky** [comment]
Thank you for your  comment and for highlighting the compatibility issue with GNU Octave. I appreciate your suggestion to make the table creation conditional on the option.verbose, which indeed seems like a practical approach to enhance compatibility.

Considering the importance of compatibility and code portability, I will rewrite the code on enclosing the table creation within the options.verbose condition, making it more adaptable to environments where the table function is not yet implemented, such as GNU Octave. Thank you.

**Comment by witkovsky** [comment]
The updated version of OEFPIL2D and OEFPIL algorithms was issued on Dec 8, 2023.
